import { Metadata } from "next";
import TestComponent from "../components/TestComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function Home() {
  return <TestComponent />;
}
